In [1]:
import pandas as pd

In [12]:
df=pd.read_excel('./외감_dp.xls')
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,Unnamed: 13,Unnamed: 14
0,KIS,Stock,Name,KIS 신용평점/0A3010,KIS 신용평점/0A3010,KIS 신용평점/0A3010,KIS 신용평점/0A3010,KIS 신용평점/0A3010,KIS 신용평점/0A3010,KIS 신용평점/0A3010,KIS 신용평점/0A3010,KIS 신용평점/0A3010,KIS 신용평점/0A3010,CP 유효등급/0A3030,회사채 유효등급/0A3040
1,000083,NaN,청우화학(주),3,3,3,3,3,3,3,3,3,3,NaN,NaN
2,000292,059210,(주)메타바이오메드,5,7,5,6,5,5,5,5,4,4,NaN,NaN
3,000356,NaN,코디아산업(주),5,6,6,5,3,2,3,4,4,3,NaN,NaN
4,000366,NaN,(주)코라,3,6,7,7,6,7,7,6,4,5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37025,V10366,NaN,(주)우전지앤에프,10,7,9,8,7,6,6,6,6,4,NaN,NaN
37026,X01379,NaN,다마요팩(주),6,5,5,6,6,6,5,6,6,6,NaN,NaN
37027,X57312,NaN,(주)에스엘씨,8,7,6,3,3,3,7,5,3,3,NaN,NaN
37028,X91216,NaN,농업회사법인한국양계(주),6,6,5,5,5,6,6,4,4,4,NaN,NaN
37029,Y32604,NaN,(주)메디라인액티브코리아,7,7,7,5,6,5,5,4,4,5,NaN,NaN

In [ ]:
import numpy as np

# O-Score의 계수
coefficients = {
    '유동자산회전률':-0.47765086
    '총자산대비잉여현금흐름':-0.53785436
    '자기자본구성비율':-0.49360789
    'log자산총계':-0.94238478
    '자기자본회전률':0.08646556
    '순운전자본회전률':0.98107367
    '자기자본증가율':-0.19544705
    '총자본증가율':-0.44094258
    '총자산대비현금흐름':0.37036301
    '총자본투자효율':-0.26458857

    'constant': -0.90495308
}

# O-Score 계산
df['dp_score'] = coefficients['constant']
df['dp_score'] += coefficients['유동자산회전률'] * df['유동자산회전률']
df['dp_score'] += coefficients['총자산대비잉여현금흐름'] * df['총자산대비잉여현금흐름']
df['dp_score'] += coefficients['자기자본구성비율'] * df['자기자본구성비율']
df['dp_score'] += coefficients['log자산총계'] * df['log자산총계']
df['dp_score'] += coefficients['자기자본회전률'] * df['자기자본회전률']
df['dp_score'] += coefficients['순운전자본회전률'] * df['순운전자본회전률']
df['dp_score'] += coefficients['자기자본증가율'] * df['자기자본증가율']
df['dp_score'] += coefficients['총자본증가율'] * df['총자본증가율']
df['dp_score'] += coefficients['총자산대비현금흐름'] * df['총자산대비현금흐름']
df['dp_score'] += coefficients['총자본투자효율'] * df['총자본투자효율']

# 로지스틱 함수를 이용해 부도 확률 계산
df['default_probability'] = 1 / (1 + np.exp(-df['dp_score']))