# 파생변수 생성

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('../data/t-1_raw_외감.csv', encoding='euc-kr')

In [7]:
df

,회사명,거래소코드,회계년도,산업분류코드,부채비율,당좌비율,유동비율,이자보상배율,OCF(천원),이자비용(천원),...,자산총계(천원),부채총계(천원),자본총계(천원),산업분류,자본금(천원),영업손익(천원),연구개발비(천원),자본잠식률,Year,t-1감사의견코드
0,(주)포스코건설,10000,2012/12,41,173.49,124.35,149.99,1.479000e+01,123580817.0,45854000.0,...,9.200763e+09,6.371979e+09,2.828785e+09,건설업,183615000.0,325556346.0,0.0,-14.406065,2012,0.0
1,(주)포스코건설,10000,2013/12,41,130.89,120.59,146.23,1.384000e+01,383458439.0,44520000.0,...,8.641621e+09,5.695142e+09,2.946479e+09,건설업,183615000.0,448381418.0,0.0,-15.047049,2013,0.0
2,(주)포스코건설,10000,2014/12,41,120.92,125.34,153.62,6.330000e+00,-81029724.0,55648000.0,...,8.366265e+09,5.380361e+09,2.985904e+09,건설업,183615000.0,322993697.0,0.0,-15.261763,2014,0.0
3,(주)포스코건설,10000,2015/12,41,100.59,145.66,164.20,7.330000e+00,645297841.0,61387000.0,...,8.244069e+09,4.904907e+09,3.339162e+09,건설업,209033470.0,138905344.0,0.0,-14.974293,2015,0.0
4,(주)포스코건설,10000,2016/12,41,145.02,109.23,133.86,-8.080000e+00,-616838633.0,45847000.0,...,7.823514e+09,5.242529e+09,2.580985e+09,건설업,209033470.0,-509016997.0,0.0,-11.347233,2016,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195595,주식회사디벨롭파트너스,107270,2021/12,68,207716.86,159.52,159.90,1.030000e+00,-4899222.0,334246.0,...,1.962570e+07,1.961626e+07,9.444000e+03,부동산업,1000.0,345351.0,0.0,-8.444000,2021,0.0
195596,주식회사비바웨이브,107272,2021/12,47,12.22,772.88,933.46,1.000000e+09,-1246669.0,0.0,...,1.271395e+07,1.384557e+06,1.132939e+07,도매 및 소매업,21124.0,-2479774.0,0.0,-535.327968,2021,0.0
195597,(주)경기화학물류,107273,2021/12,49,192.42,259.26,336.89,3.220000e+00,-533800.0,179755.0,...,1.439139e+07,9.469859e+06,4.921531e+06,운수 및 창고업,900000.0,578423.0,0.0,-4.468368,2021,1.0
195598,주식회사일그램,107276,2021/12,71,99.28,1838.90,1838.90,2.574000e+01,3232717.0,108993.0,...,1.332789e+07,6.639830e+06,6.688061e+06,"전문, 과학 및 기술 서비스업",500000.0,2805172.0,0.0,-12.376122,2021,0.0
195599,(주)두산종합건재,107278,2021/12,46,273.78,376.36,394.26,1.130000e+00,-2107626.0,241431.0,...,1.369579e+07,1.003170e+07,3.664089e+06,도매 및 소매업,100000.0,271995.0,720.0,-35.640890,2021,1.0

In [8]:
# 결측치 확인
df.isna().sum()

회사명                   0
거래소코드                 0
회계년도                  0
산업분류코드                0
부채비율                 60
당좌비율                 60
유동비율                 60
이자보상배율               60
OCF(천원)              58
이자비용(천원)             58
차입금의존도               60
자기자본구성비율             60
당기순이익(천원)            58
감가상각비(백만원)         1385
금융비용(백만원)           204
단기차입금(천원)            58
유동성장기부채(천원)          58
장기차입금(천원)            58
법인세비용차감전손익(백만원)      75
매출액영업이익률             60
자기자본순이익률             60
총자본순이익률              60
매출액(천원)              58
총자본회전률               60
자기자본회전률              60
운전자본회전률              60
순운전자본회전률             60
재고자산회전률              60
당좌자산회전률              60
유동자산회전률              60
매출액증가율               59
총자본증가율               59
자기자본증가율              59
순이익증가율               59
유형자산증가율              59
유동자산증가율              59
재고자산증가율              59
영업이익증가율              59
총자본투자효율              69
부가가치율                69
노동소득분배율              69
자본분배율                69
이윤분배율                69
ICF(천원)              58
FCF(천원)              58
자산총계(천원)             58
부채총계(천원)             58
자본총계(천원)             58
산업분류                  0
자본금(천원)              58
영업손익(천원)             58
연구개발비(천원)            58
자본잠식률                67
Year                  0
t-1감사의견코드             0
dtype: int64

In [9]:
df.drop('자본잠식률', axis=1, inplace=True)

In [10]:
df.dropna(subset='자산총계(천원)', axis=0, inplace=True)

In [11]:
df[df['법인세비용차감전손익(백만원)'].isna()==True]['t-1감사의견코드'].value_counts()

0.0    18
Name: t-1감사의견코드, dtype: int64

In [12]:
df.dropna(subset='법인세비용차감전손익(백만원)', axis=0, inplace=True)

In [13]:
df.isna().sum()

회사명                   0
거래소코드                 0
회계년도                  0
산업분류코드                0
부채비율                  1
당좌비율                  1
유동비율                  1
이자보상배율                1
OCF(천원)               0
이자비용(천원)              0
차입금의존도                1
자기자본구성비율              1
당기순이익(천원)             0
감가상각비(백만원)         1310
금융비용(백만원)           130
단기차입금(천원)             0
유동성장기부채(천원)           0
장기차입금(천원)             0
법인세비용차감전손익(백만원)       0
매출액영업이익률              1
자기자본순이익률              1
총자본순이익률               1
매출액(천원)               0
총자본회전률                0
자기자본회전률               0
운전자본회전률               0
순운전자본회전률              0
재고자산회전률               0
당좌자산회전률               0
유동자산회전률               0
매출액증가율                0
총자본증가율                0
자기자본증가율               0
순이익증가율                0
유형자산증가율               0
유동자산증가율               0
재고자산증가율               0
영업이익증가율               0
총자본투자효율               5
부가가치율                 5
노동소득분배율               5
자본분배율                 5
이윤분배율                 5
ICF(천원)               0
FCF(천원)               0
자산총계(천원)              0
부채총계(천원)              0
자본총계(천원)              0
산업분류                  0
자본금(천원)               0
영업손익(천원)              0
연구개발비(천원)             0
Year                  0
t-1감사의견코드             0
dtype: int64

In [14]:
df[df['부가가치율'].isna()==True].iloc[:,-16:-11]

        총자본투자효율  부가가치율  노동소득분배율  자본분배율  이윤분배율
82561       NaN    NaN      NaN    NaN    NaN
172235      NaN    NaN      NaN    NaN    NaN
179273      NaN    NaN      NaN    NaN    NaN
188219      NaN    NaN      NaN    NaN    NaN
195000      NaN    NaN      NaN    NaN    NaN

In [15]:
df.dropna(subset='부가가치율', axis=0, inplace=True)

In [16]:
df.dropna(subset='부채비율', axis=0, inplace=True)

In [17]:
df.isna().sum()

회사명                   0
거래소코드                 0
회계년도                  0
산업분류코드                0
부채비율                  0
당좌비율                  0
유동비율                  0
이자보상배율                0
OCF(천원)               0
이자비용(천원)              0
차입금의존도                0
자기자본구성비율              0
당기순이익(천원)             0
감가상각비(백만원)         1310
금융비용(백만원)           130
단기차입금(천원)             0
유동성장기부채(천원)           0
장기차입금(천원)             0
법인세비용차감전손익(백만원)       0
매출액영업이익률              1
자기자본순이익률              1
총자본순이익률               1
매출액(천원)               0
총자본회전률                0
자기자본회전률               0
운전자본회전률               0
순운전자본회전률              0
재고자산회전률               0
당좌자산회전률               0
유동자산회전률               0
매출액증가율                0
총자본증가율                0
자기자본증가율               0
순이익증가율                0
유형자산증가율               0
유동자산증가율               0
재고자산증가율               0
영업이익증가율               0
총자본투자효율               0
부가가치율                 0
노동소득분배율               0
자본분배율                 0
이윤분배율                 0
ICF(천원)               0
FCF(천원)               0
자산총계(천원)              0
부채총계(천원)              0
자본총계(천원)              0
산업분류                  0
자본금(천원)               0
영업손익(천원)              0
연구개발비(천원)             0
Year                  0
t-1감사의견코드             0
dtype: int64

In [18]:
df[df['매출액영업이익률'].isna()==True]

,회사명,거래소코드,회계년도,산업분류코드,부채비율,당좌비율,유동비율,이자보상배율,OCF(천원),이자비용(천원),...,FCF(천원),자산총계(천원),부채총계(천원),자본총계(천원),산업분류,자본금(천원),영업손익(천원),연구개발비(천원),Year,t-1감사의견코드
106095,(주)태려,61788,2021/12,46,0.0,0.44,0.44,-0.14,-1545262.0,1583898.0,...,3439842.0,17699749.0,38840815.0,-21141065.0,도매 및 소매업,8400000.0,-224020.0,0.0,2021,0.0

In [19]:
df.dropna(subset='매출액영업이익률', axis=0, inplace=True)

In [20]:
df.isna().sum()

회사명                   0
거래소코드                 0
회계년도                  0
산업분류코드                0
부채비율                  0
당좌비율                  0
유동비율                  0
이자보상배율                0
OCF(천원)               0
이자비용(천원)              0
차입금의존도                0
자기자본구성비율              0
당기순이익(천원)             0
감가상각비(백만원)         1310
금융비용(백만원)           130
단기차입금(천원)             0
유동성장기부채(천원)           0
장기차입금(천원)             0
법인세비용차감전손익(백만원)       0
매출액영업이익률              0
자기자본순이익률              0
총자본순이익률               0
매출액(천원)               0
총자본회전률                0
자기자본회전률               0
운전자본회전률               0
순운전자본회전률              0
재고자산회전률               0
당좌자산회전률               0
유동자산회전률               0
매출액증가율                0
총자본증가율                0
자기자본증가율               0
순이익증가율                0
유형자산증가율               0
유동자산증가율               0
재고자산증가율               0
영업이익증가율               0
총자본투자효율               0
부가가치율                 0
노동소득분배율               0
자본분배율                 0
이윤분배율                 0
ICF(천원)               0
FCF(천원)               0
자산총계(천원)              0
부채총계(천원)              0
자본총계(천원)              0
산업분류                  0
자본금(천원)               0
영업손익(천원)              0
연구개발비(천원)             0
Year                  0
t-1감사의견코드             0
dtype: int64

In [21]:
df['감가상각비(백만원)'] = df['감가상각비(백만원)'].fillna(0)
df['금융비용(백만원)'] = df['금융비용(백만원)'].fillna(0)

In [22]:
df.isna().sum()

회사명                0
거래소코드              0
회계년도               0
산업분류코드             0
부채비율               0
당좌비율               0
유동비율               0
이자보상배율             0
OCF(천원)            0
이자비용(천원)           0
차입금의존도             0
자기자본구성비율           0
당기순이익(천원)          0
감가상각비(백만원)         0
금융비용(백만원)          0
단기차입금(천원)          0
유동성장기부채(천원)        0
장기차입금(천원)          0
법인세비용차감전손익(백만원)    0
매출액영업이익률           0
자기자본순이익률           0
총자본순이익률            0
매출액(천원)            0
총자본회전률             0
자기자본회전률            0
운전자본회전률            0
순운전자본회전률           0
재고자산회전률            0
당좌자산회전률            0
유동자산회전률            0
매출액증가율             0
총자본증가율             0
자기자본증가율            0
순이익증가율             0
유형자산증가율            0
유동자산증가율            0
재고자산증가율            0
영업이익증가율            0
총자본투자효율            0
부가가치율              0
노동소득분배율            0
자본분배율              0
이윤분배율              0
ICF(천원)            0
FCF(천원)            0
자산총계(천원)           0
부채총계(천원)           0
자본총계(천원)           0
산업분류               0
자본금(천원)            0
영업손익(천원)           0
연구개발비(천원)          0
Year               0
t-1감사의견코드          0
dtype: int64

In [23]:
df

,회사명,거래소코드,회계년도,산업분류코드,부채비율,당좌비율,유동비율,이자보상배율,OCF(천원),이자비용(천원),...,FCF(천원),자산총계(천원),부채총계(천원),자본총계(천원),산업분류,자본금(천원),영업손익(천원),연구개발비(천원),Year,t-1감사의견코드
0,(주)포스코건설,10000,2012/12,41,173.49,124.35,149.99,1.479000e+01,123580817.0,45854000.0,...,121474510.0,9.200763e+09,6.371979e+09,2.828785e+09,건설업,183615000.0,325556346.0,0.0,2012,0.0
1,(주)포스코건설,10000,2013/12,41,130.89,120.59,146.23,1.384000e+01,383458439.0,44520000.0,...,-163581203.0,8.641621e+09,5.695142e+09,2.946479e+09,건설업,183615000.0,448381418.0,0.0,2013,0.0
2,(주)포스코건설,10000,2014/12,41,120.92,125.34,153.62,6.330000e+00,-81029724.0,55648000.0,...,-27739975.0,8.366265e+09,5.380361e+09,2.985904e+09,건설업,183615000.0,322993697.0,0.0,2014,0.0
3,(주)포스코건설,10000,2015/12,41,100.59,145.66,164.20,7.330000e+00,645297841.0,61387000.0,...,391500030.0,8.244069e+09,4.904907e+09,3.339162e+09,건설업,209033470.0,138905344.0,0.0,2015,0.0
4,(주)포스코건설,10000,2016/12,41,145.02,109.23,133.86,-8.080000e+00,-616838633.0,45847000.0,...,146163668.0,7.823514e+09,5.242529e+09,2.580985e+09,건설업,209033470.0,-509016997.0,0.0,2016,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195595,주식회사디벨롭파트너스,107270,2021/12,68,207716.86,159.52,159.90,1.030000e+00,-4899222.0,334246.0,...,10001000.0,1.962570e+07,1.961626e+07,9.444000e+03,부동산업,1000.0,345351.0,0.0,2021,0.0
195596,주식회사비바웨이브,107272,2021/12,47,12.22,772.88,933.46,1.000000e+09,-1246669.0,0.0,...,8132821.0,1.271395e+07,1.384557e+06,1.132939e+07,도매 및 소매업,21124.0,-2479774.0,0.0,2021,0.0
195597,(주)경기화학물류,107273,2021/12,49,192.42,259.26,336.89,3.220000e+00,-533800.0,179755.0,...,1039220.0,1.439139e+07,9.469859e+06,4.921531e+06,운수 및 창고업,900000.0,578423.0,0.0,2021,1.0
195598,주식회사일그램,107276,2021/12,71,99.28,1838.90,1838.90,2.574000e+01,3232717.0,108993.0,...,6879900.0,1.332789e+07,6.639830e+06,6.688061e+06,"전문, 과학 및 기술 서비스업",500000.0,2805172.0,0.0,2021,0.0
195599,(주)두산종합건재,107278,2021/12,46,273.78,376.36,394.26,1.130000e+00,-2107626.0,241431.0,...,2865000.0,1.369579e+07,1.003170e+07,3.664089e+06,도매 및 소매업,100000.0,271995.0,720.0,2021,1.0

In [24]:
df['파생이자보상배율'] = (df['OCF(천원)']/df['이자비용(천원)'])*100
df['부채상환계수'] = ((df['당기순이익(천원)']+(df['감가상각비(백만원)']*1000)+(df['금융비용(백만원)']*1000))/(df['단기차입금(천원)']+df['유동성장기부채(천원)']+(df['금융비용(백만원)']*1000)))*100
df['장기/EBITDA'] = (df['장기차입금(천원)']/((df['법인세비용차감전손익(백만원)']*1000)+(df['감가상각비(백만원)']*1000)+df['이자비용(천원)']))*100
df['금융대비매출액'] = ((df['금융비용(백만원)']*1000)/df['매출액(천원)'])*100
df['전체현금흐름(천원)'] = df['OCF(천원)']+df['ICF(천원)']+df['FCF(천원)']
df['연구개발비대비매출액'] = (df['연구개발비(천원)']/df['매출액(천원)'])*100

In [25]:
df

,회사명,거래소코드,회계년도,산업분류코드,부채비율,당좌비율,유동비율,이자보상배율,OCF(천원),이자비용(천원),...,영업손익(천원),연구개발비(천원),Year,t-1감사의견코드,파생이자보상배율,부채상환계수,장기/EBITDA,금융대비매출액,전체현금흐름(천원),연구개발비대비매출액
0,(주)포스코건설,10000,2012/12,41,173.49,124.35,149.99,1.479000e+01,123580817.0,45854000.0,...,325556346.0,0.0,2012,0.0,269.509349,54.202256,15.307325,-0.004855,-8.613919e+07,0.000000
1,(주)포스코건설,10000,2013/12,41,130.89,120.59,146.23,1.384000e+01,383458439.0,44520000.0,...,448381418.0,0.0,2013,0.0,861.317248,19.960468,111.055604,-0.139800,6.952441e+07,0.000000
2,(주)포스코건설,10000,2014/12,41,120.92,125.34,153.62,6.330000e+00,-81029724.0,55648000.0,...,322993697.0,0.0,2014,0.0,-145.611206,19.238487,309.497126,0.219967,-6.363516e+08,0.000000
3,(주)포스코건설,10000,2015/12,41,100.59,145.66,164.20,7.330000e+00,645297841.0,61387000.0,...,138905344.0,0.0,2015,0.0,1051.196248,-6.632979,157.477984,0.160693,1.042678e+09,0.000000
4,(주)포스코건설,10000,2016/12,41,145.02,109.23,133.86,-8.080000e+00,-616838633.0,45847000.0,...,-509016997.0,0.0,2016,0.0,-1345.428562,-51.533778,-8.091255,-0.908908,-7.153034e+08,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195595,주식회사디벨롭파트너스,107270,2021/12,68,207716.86,159.52,159.90,1.030000e+00,-4899222.0,334246.0,...,345351.0,0.0,2021,0.0,-1465.753367,102.608991,2890.624548,64.730000,1.659520e+05,0.000000
195596,주식회사비바웨이브,107272,2021/12,47,12.22,772.88,933.46,1.000000e+09,-1246669.0,0.0,...,-2479774.0,0.0,2021,0.0,-inf,12563.897059,-0.000000,-0.116222,6.199390e+06,0.000000
195597,(주)경기화학물류,107273,2021/12,49,192.42,259.26,336.89,3.220000e+00,-533800.0,179755.0,...,578423.0,0.0,2021,1.0,-296.959751,450.781076,785.224429,1.388176,2.867050e+05,0.000000
195598,주식회사일그램,107276,2021/12,71,99.28,1838.90,1838.90,2.574000e+01,3232717.0,108993.0,...,2805172.0,0.0,2021,0.0,2965.985889,3121.245016,201.925506,0.381115,4.237890e+05,0.000000
195599,(주)두산종합건재,107278,2021/12,46,273.78,376.36,394.26,1.130000e+00,-2107626.0,241431.0,...,271995.0,720.0,2021,1.0,-872.972402,367.291856,1408.886066,1.187318,-6.799700e+04,0.012941

In [26]:
df['t-1감사의견코드'].value_counts()

0.0    182043
1.0     13474
Name: t-1감사의견코드, dtype: int64

In [27]:
13474 / (182043 + 13474)

0.06891472352787738

In [28]:
df.isna().sum()

회사명                    0
거래소코드                  0
회계년도                   0
산업분류코드                 0
부채비율                   0
당좌비율                   0
유동비율                   0
이자보상배율                 0
OCF(천원)                0
이자비용(천원)               0
차입금의존도                 0
자기자본구성비율               0
당기순이익(천원)              0
감가상각비(백만원)             0
금융비용(백만원)              0
단기차입금(천원)              0
유동성장기부채(천원)            0
장기차입금(천원)              0
법인세비용차감전손익(백만원)        0
매출액영업이익률               0
자기자본순이익률               0
총자본순이익률                0
매출액(천원)                0
총자본회전률                 0
자기자본회전률                0
운전자본회전률                0
순운전자본회전률               0
재고자산회전률                0
당좌자산회전률                0
유동자산회전률                0
매출액증가율                 0
총자본증가율                 0
자기자본증가율                0
순이익증가율                 0
유형자산증가율                0
유동자산증가율                0
재고자산증가율                0
영업이익증가율                0
총자본투자효율                0
부가가치율                  0
노동소득분배율                0
자본분배율                  0
이윤분배율                  0
ICF(천원)                0
FCF(천원)                0
자산총계(천원)               0
부채총계(천원)               0
자본총계(천원)               0
산업분류                   0
자본금(천원)                0
영업손익(천원)               0
연구개발비(천원)              0
Year                   0
t-1감사의견코드              0
파생이자보상배율             271
부채상환계수                34
장기/EBITDA             39
금융대비매출액              529
전체현금흐름(천원)             0
연구개발비대비매출액         10047
dtype: int64

In [33]:
df['산업분류코드'].value_counts()

68    30805
46    17223
41    14240
29    10332
30     8215
      ...
86       25
8        22
12       22
84       12
98        1
Name: 산업분류코드, Length: 74, dtype: int64

In [34]:
df[['산업분류코드', '산업분류']]

        산업분류코드              산업분류
0           41               건설업
1           41               건설업
2           41               건설업
3           41               건설업
4           41               건설업
...        ...               ...
195595      68              부동산업
195596      47          도매 및 소매업
195597      49          운수 및 창고업
195598      71  전문, 과학 및 기술 서비스업
195599      46          도매 및 소매업

[195517 rows x 2 columns]

In [37]:
len(df['거래소코드'].unique()) - 13474

33664

In [39]:
13474/(33664+13474)

0.28584157155585727

In [40]:
df[df['매출액(천원)']==0]

,회사명,거래소코드,회계년도,산업분류코드,부채비율,당좌비율,유동비율,이자보상배율,OCF(천원),이자비용(천원),...,영업손익(천원),연구개발비(천원),Year,t-1감사의견코드,파생이자보상배율,부채상환계수,장기/EBITDA,금융대비매출액,전체현금흐름(천원),연구개발비대비매출액
408,동양인터내셔널(주),10079,2016/12,46,5.34,305.44,305.44,-6.130000e+00,12613.0,139687.0,...,-856064.0,0.0,2016,0.0,9.029473e+00,-4004.959062,-0.000000,inf,-1413756.0,NaN
409,동양인터내셔널(주),10079,2017/12,46,29.30,1388.44,1388.44,-2.960000e+00,1035385.0,145514.0,...,-430597.0,0.0,2017,0.0,7.115363e+02,83522.190984,-0.000000,-inf,-476289.0,NaN
410,동양인터내셔널(주),10079,2018/12,46,22.59,2065.01,2065.01,-2.110000e+00,-376793.0,126949.0,...,-268027.0,0.0,2018,0.0,-2.968066e+02,183.854099,-0.000000,-inf,-311516.0,NaN
460,한화글로벌에셋주식회사,10095,2021/12,68,2.19,613.64,4286.13,1.000000e+09,-3660600.0,0.0,...,-2622660.0,0.0,2021,0.0,-inf,-19869.937677,0.000000,-inf,-19439887.0,NaN
629,주식회사화승티엔드씨아이,10218,2020/12,22,62.12,6.75,6.75,-1.400000e-01,14167550.0,136074.0,...,-19031.0,0.0,2020,0.0,1.041165e+04,57.777709,31.626074,inf,450893.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195573,에스알산업주식회사,107180,2021/12,68,0.00,8.41,106.25,1.000000e+09,-18055696.0,0.0,...,-283221.0,0.0,2021,0.0,-inf,-1.563033,-531.439770,-inf,1178921.0,NaN
195574,태안도시에너지주식회사,107181,2021/12,41,574.77,1.35,1.35,1.000000e+09,-3635971.0,0.0,...,-156994.0,0.0,2021,1.0,-inf,74760.476190,-6911.155048,-inf,-1236071.0,NaN
195577,(주)로얄종합개발,107185,2021/12,41,0.00,46914.32,48884.97,-1.876000e+01,-13758502.0,16450.0,...,-308615.0,0.0,2021,0.0,-8.363831e+04,-2985.614714,-4631.314301,inf,236364.0,NaN
195592,(주)그린씨티개발,107262,2021/12,68,0.00,45.78,2078.72,-3.520000e+00,-39307517.0,1610546.0,...,-5669452.0,0.0,2021,0.0,-2.440633e+03,-218.442300,-719.935500,inf,-96629.0,NaN
195593,그린씨티제일차,107263,2021/12,68,0.00,81.08,81.08,-1.000000e-02,-1061217.0,1048188.0,...,-13186.0,0.0,2021,0.0,-1.012430e+02,-83.211356,3989.729104,-inf,2981.0,NaN

In [41]:
df['이자비용(천원)'].value_counts()

0.0         24556
1.0            57
2.0            55
3.0            44
5.0            32
            ...
835368.0        1
933635.0        1
878173.0        1
954777.0        1
108993.0        1
Name: 이자비용(천원), Length: 153818, dtype: int64

In [ ]:
df['자기']

In [47]:
df[(df['매출액(천원)']==0)]['자기자본회전률'].value_counts()

0.00    10338
4.33        1
3.95        1
3.19        1
3.11        1
1.72        1
0.37        1
0.94        1
0.33        1
Name: 자기자본회전률, dtype: int64

In [48]:
df[['산업분류코드', '산업분류']]

        산업분류코드              산업분류
0           41               건설업
1           41               건설업
2           41               건설업
3           41               건설업
4           41               건설업
...        ...               ...
195595      68              부동산업
195596      47          도매 및 소매업
195597      49          운수 및 창고업
195598      71  전문, 과학 및 기술 서비스업
195599      46          도매 및 소매업

[195517 rows x 2 columns]

In [49]:
import matplotlib.pyplot as plt
import

In [ ]:
## boxplot

def dist(df_1,target,col_n, row_n):
    plt.rcParams['font.family'] = "Malgun Gothic"
    plt.rcParams['axes.unicode_minus'] = False # 마이너스숫자 출력처리

    fig, ax = plt.subplots(ncols=col_n, nrows=row_n, figsize=(20, row_n*5))

    for i, col in enumerate(df_1.columns[:]):
        sns.boxplot(y=col,x=target, ax=ax[int(i/col_n), int(i%col_n)],data=df_1) # df_1의 데이터를 빨간색으로 박스플롯 그리기
       
dist(df_float,df["target_2"],8,4)
plt.show() # 박스플롯 출력|

In [50]:
df.sort_values(by='부채비율', ascending=False)

,회사명,거래소코드,회계년도,산업분류코드,부채비율,당좌비율,유동비율,이자보상배율,OCF(천원),이자비용(천원),...,영업손익(천원),연구개발비(천원),Year,t-1감사의견코드,파생이자보상배율,부채상환계수,장기/EBITDA,금융대비매출액,전체현금흐름(천원),연구개발비대비매출액
194393,논산아리스타컨트리클럽주식회사,105715,2021/12,64,2.373601e+09,100.00,100.00,1.000000e+09,0.0,0.0,...,0.0,0.0,2021,0.0,NaN,NaN,inf,0.000000,1.0,0.000000
194362,(주)속초에스피씨,105679,2021/12,68,2.194869e+08,100.01,100.01,0.000000e+00,-985.0,1160579.0,...,-999.0,0.0,2021,0.0,-0.084871,9950.000000,2.742351e+03,-inf,1.0,NaN
194866,주식회사빅히트파트너스,106282,2021/12,71,1.892217e+08,100.15,100.15,1.000000e+09,-966.0,0.0,...,-976.0,0.0,2021,0.0,-inf,-97.704591,-1.451613e+07,-0.001303,91.0,0.000000
189580,주식회사제이피컴퍼니,100155,2021/12,66,4.000000e+07,0.00,0.00,1.000000e+00,0.0,433325.0,...,433325.0,0.0,2021,0.0,0.000000,100.000000,9.230947e+03,7.586753,0.0,0.000000
141907,주식회사에스엠케이산업,73911,2014/12,68,3.184806e+07,476.85,1628.13,1.000000e+09,-20576816.0,0.0,...,0.0,0.0,2014,1.0,-inf,NaN,inf,NaN,9315120.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55518,주식회사은진,44439,2014/12,29,0.000000e+00,21.55,26.99,-5.000000e-02,-18366.0,522055.0,...,-25028.0,7060.0,2014,0.0,-3.518020,4.134663,0.000000e+00,5.843331,-14313.0,0.083707
55517,주식회사은진,44439,2013/12,29,0.000000e+00,30.96,35.29,-3.950000e+00,-1179568.0,609074.0,...,-2403565.0,142292.0,2013,0.0,-193.665794,-18.872948,-8.547338e+00,3.846747,-375618.0,0.947566
121046,주식회사태평동락커뮤니티,66498,2012/12,68,0.000000e+00,3.29,98.61,1.000000e+09,-3236389.0,0.0,...,-66746.0,0.0,2012,1.0,-inf,-1.662471,-0.000000e+00,-inf,107697.0,NaN
153651,주식회사동남개발,78953,2016/06,68,0.000000e+00,49.54,58.69,-5.700000e-01,-269244.0,1196440.0,...,-687875.0,0.0,2016,0.0,-22.503761,-7.042358,-0.000000e+00,inf,-249663.0,NaN
145674,(주)레이전트리,76145,2015/12,47,-6.280000e+00,0.00,0.00,1.000000e+09,2404334.0,0.0,...,6068349.0,0.0,2015,1.0,inf,897.639513,0.000000e+00,-0.226669,2409469.0,0.000000

In [51]:
df[df['부채총계(천원)']<0]

,회사명,거래소코드,회계년도,산업분류코드,부채비율,당좌비율,유동비율,이자보상배율,OCF(천원),이자비용(천원),...,영업손익(천원),연구개발비(천원),Year,t-1감사의견코드,파생이자보상배율,부채상환계수,장기/EBITDA,금융대비매출액,전체현금흐름(천원),연구개발비대비매출액
145674,(주)레이전트리,76145,2015/12,47,-6.28,0.0,0.0,999999999.0,2404334.0,0.0,...,6068349.0,0.0,2015,1.0,inf,897.639513,0.0,-0.226669,2409469.0,0.0